
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Xyjor
 */
public class StackQueue extends javax.swing.JFrame {
    private Stack stack = new Stack(10);
    private Queue queue = new Queue(10);
    private List<String> actions = new ArrayList<>(); // For Undo/Redo
    private List<String> redoActions = new ArrayList<>(); // For Redo
    private void updateUndoRedoOutput() {
        prob1TArea.setText("Actions: " + actions + "\nRedo: " + redoActions);
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StackQueue.class.getName());

    /**
     * Creates new form StackQueue
     */
    public StackQueue() {
        initComponents();
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        stackTField = new javax.swing.JTextField();
        SpushBttn = new javax.swing.JButton();
        SpopBttn = new javax.swing.JButton();
        SpeekBttn = new javax.swing.JButton();
        SdisplayBttn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        StackTArea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        queueTField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        queueTArea = new javax.swing.JTextArea();
        QenqueueBttn = new javax.swing.JButton();
        QdequeueBttn = new javax.swing.JButton();
        QpeekBttn = new javax.swing.JButton();
        QdisplayBttn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        perfactBttn = new javax.swing.JButton();
        undoBttn = new javax.swing.JButton();
        redoBttn = new javax.swing.JButton();
        prob1TField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        prob1TArea = new javax.swing.JTextArea();
        addcostuemrBttn = new javax.swing.JButton();
        servecostumerBttn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        prob2TArea = new javax.swing.JTextArea();
        checkBttn = new javax.swing.JButton();
        costumerTField = new javax.swing.JTextField();
        prob3TField = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        prob3Tarea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(102, 102, 102));

        jPanel1.setLayout(new java.awt.GridBagLayout());

        stackTField.setBackground(new java.awt.Color(255, 255, 255));
        stackTField.setForeground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 293;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 20, 0, 0);
        jPanel1.add(stackTField, gridBagConstraints);

        SpushBttn.setText("PUSH");
        SpushBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpushBttnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 26, 0, 0);
        jPanel1.add(SpushBttn, gridBagConstraints);

        SpopBttn.setText("POP");
        SpopBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpopBttnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        jPanel1.add(SpopBttn, gridBagConstraints);

        SpeekBttn.setText("PEEK");
        SpeekBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpeekBttnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        jPanel1.add(SpeekBttn, gridBagConstraints);

        SdisplayBttn.setText("DISPLAY");
        SdisplayBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SdisplayBttnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        jPanel1.add(SdisplayBttn, gridBagConstraints);

        StackTArea.setEditable(false);
        StackTArea.setBackground(new java.awt.Color(255, 255, 255));
        StackTArea.setColumns(20);
        StackTArea.setForeground(new java.awt.Color(0, 0, 0));
        StackTArea.setRows(5);
        jScrollPane1.setViewportView(StackTArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 268;
        gridBagConstraints.ipady = 132;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(19, 18, 364, 95);
        jPanel1.add(jScrollPane1, gridBagConstraints);

        jTabbedPane1.addTab("tab1", jPanel1);

        queueTField.setBackground(new java.awt.Color(255, 255, 255));
        queueTField.setForeground(new java.awt.Color(0, 0, 0));

        queueTArea.setEditable(false);
        queueTArea.setBackground(new java.awt.Color(255, 255, 255));
        queueTArea.setColumns(20);
        queueTArea.setForeground(new java.awt.Color(0, 0, 0));
        queueTArea.setRows(5);
        jScrollPane2.setViewportView(queueTArea);

        QenqueueBttn.setText("ENQUEUE");
        QenqueueBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QenqueueBttnActionPerformed(evt);
            }
        });

        QdequeueBttn.setText("DEQUEUE");
        QdequeueBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QdequeueBttnActionPerformed(evt);
            }
        });

        QpeekBttn.setText("PEEK");
        QpeekBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QpeekBttnActionPerformed(evt);
            }
        });

        QdisplayBttn.setText("DISPLAY");
        QdisplayBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QdisplayBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(QenqueueBttn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(QdequeueBttn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(QpeekBttn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(QdisplayBttn))
                    .addComponent(queueTField))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(queueTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(QenqueueBttn)
                            .addComponent(QdequeueBttn)
                            .addComponent(QpeekBttn)
                            .addComponent(QdisplayBttn)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(384, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        perfactBttn.setText("Perform Action");
        perfactBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfactBttnActionPerformed(evt);
            }
        });

        undoBttn.setText("Undo");
        undoBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoBttnActionPerformed(evt);
            }
        });

        redoBttn.setText("Redo");
        redoBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redoBttnActionPerformed(evt);
            }
        });

        prob1TField.setBackground(new java.awt.Color(255, 255, 255));
        prob1TField.setForeground(new java.awt.Color(0, 0, 0));

        prob1TArea.setEditable(false);
        prob1TArea.setBackground(new java.awt.Color(255, 255, 255));
        prob1TArea.setColumns(20);
        prob1TArea.setForeground(new java.awt.Color(0, 0, 0));
        prob1TArea.setRows(5);
        jScrollPane3.setViewportView(prob1TArea);

        addcostuemrBttn.setText("Add Costumer");
        addcostuemrBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcostuemrBttnActionPerformed(evt);
            }
        });

        servecostumerBttn.setText("Serve Costumer");
        servecostumerBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servecostumerBttnActionPerformed(evt);
            }
        });

        prob2TArea.setEditable(false);
        prob2TArea.setBackground(new java.awt.Color(255, 255, 255));
        prob2TArea.setColumns(20);
        prob2TArea.setForeground(new java.awt.Color(0, 0, 0));
        prob2TArea.setRows(5);
        jScrollPane4.setViewportView(prob2TArea);

        checkBttn.setText("Check");
        checkBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBttnActionPerformed(evt);
            }
        });

        costumerTField.setBackground(new java.awt.Color(255, 255, 255));
        costumerTField.setForeground(new java.awt.Color(0, 0, 0));

        prob3TField.setBackground(new java.awt.Color(255, 255, 255));
        prob3TField.setForeground(new java.awt.Color(0, 0, 0));

        prob3Tarea.setEditable(false);
        prob3Tarea.setBackground(new java.awt.Color(255, 255, 255));
        prob3Tarea.setColumns(20);
        prob3Tarea.setForeground(new java.awt.Color(0, 0, 0));
        prob3Tarea.setRows(5);
        jScrollPane5.setViewportView(prob3Tarea);

        jLabel1.setText("Undo/Redo Simulation");

        jLabel2.setText("Customer Queue Management");

        jLabel3.setText("Palindrome Checker");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(prob1TField)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(perfactBttn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(undoBttn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(redoBttn)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(addcostuemrBttn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(servecostumerBttn))
                    .addComponent(costumerTField)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane5)
                        .addComponent(prob3TField, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(70, 70, 70)
                            .addComponent(checkBttn)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(53, 53, 53)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(perfactBttn)
                    .addComponent(undoBttn)
                    .addComponent(redoBttn)
                    .addComponent(addcostuemrBttn)
                    .addComponent(servecostumerBttn)
                    .addComponent(checkBttn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prob1TField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(costumerTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prob3TField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane5))
                .addContainerGap(295, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 784, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void checkBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBttnActionPerformed
         String input = prob3TField.getText().toLowerCase().replaceAll("\\s+", "");
        Stack s = new Stack(input.length());
        Queue q = new Queue(input.length());
        for (char c : input.toCharArray()) {
            s.push(c);
            q.enqueue(c);
        }
        boolean isPalindrome = true;
        while (!s.isEmpty() && !q.isEmpty()) {
            if (s.peek() != q.peek()) {
                isPalindrome = false;
                break;
            }
            s.pop();
            q.dequeue();
        }
        prob3Tarea.setText("Is palindrome: " + isPalindrome);
    }//GEN-LAST:event_checkBttnActionPerformed

    private void SpushBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpushBttnActionPerformed
       try {
            int value = Integer.parseInt(stackTField.getText());
            stack.push(value);
            StackTArea.setText(stack.display());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Enter a valid integer.");
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_SpushBttnActionPerformed

    private void SpopBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpopBttnActionPerformed
        try {
            stack.pop();
            StackTArea.setText(stack.display());
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_SpopBttnActionPerformed

    private void SdisplayBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SdisplayBttnActionPerformed
        StackTArea.setText(stack.display());
    }//GEN-LAST:event_SdisplayBttnActionPerformed

    private void SpeekBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpeekBttnActionPerformed
        try {
            int top = stack.peek();
            StackTArea.setText("Top: " + top + "\n" + stack.display());
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_SpeekBttnActionPerformed

    private void QenqueueBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QenqueueBttnActionPerformed
         try {
            int value = Integer.parseInt(queueTField.getText());
            queue.enqueue(value);
            queueTArea.setText(queue.display());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Enter a valid integer.");
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_QenqueueBttnActionPerformed

    private void QdequeueBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QdequeueBttnActionPerformed
        try {
            queue.dequeue();
            queueTArea.setText(stack.display());
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_QdequeueBttnActionPerformed

    private void QpeekBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QpeekBttnActionPerformed
       try {
            int top = queue.peek();
            queueTArea.setText("Top: " + top + "\n" + queue.display());
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_QpeekBttnActionPerformed

    private void QdisplayBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QdisplayBttnActionPerformed
        queueTArea.setText(queue.display());
    }//GEN-LAST:event_QdisplayBttnActionPerformed

    private void perfactBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfactBttnActionPerformed
        String action = prob1TField.getText();
        if (!action.isEmpty()) {
            actions.add(action);
            redoActions.clear(); // Clear redo on new action
            updateUndoRedoOutput();
        }
    }//GEN-LAST:event_perfactBttnActionPerformed

    private void undoBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoBttnActionPerformed
        if (!actions.isEmpty()) {
            String undone = actions.remove(actions.size() - 1);
            redoActions.add(undone);
            updateUndoRedoOutput();
        }
    }//GEN-LAST:event_undoBttnActionPerformed

    private void redoBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redoBttnActionPerformed
        if (!redoActions.isEmpty()) {
            String redone = redoActions.remove(redoActions.size() - 1);
            actions.add(redone);
            updateUndoRedoOutput();
        }
    }//GEN-LAST:event_redoBttnActionPerformed

    private void addcostuemrBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcostuemrBttnActionPerformed
        String customer = costumerTField.getText();
        if (!customer.isEmpty()) {
            // For simplicity, use string length as int value (or modify Queue to handle strings)
            queue.enqueue(customer.length()); // Placeholder
            prob2TArea.setText(queue.display());
        }
    }//GEN-LAST:event_addcostuemrBttnActionPerformed

    private void servecostumerBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servecostumerBttnActionPerformed
        try {
        if (!queue.isEmpty()) {
            int servedCustomer = queue.peek();
            queue.dequeue();
            JOptionPane.showMessageDialog(this, "Served customer: " + servedCustomer);
            prob3Tarea.setText(queue.display());
        } else {
            JOptionPane.showMessageDialog(this, "No customers in queue to serve.");
        }
    } catch (RuntimeException e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_servecostumerBttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StackQueue().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton QdequeueBttn;
    private javax.swing.JButton QdisplayBttn;
    private javax.swing.JButton QenqueueBttn;
    private javax.swing.JButton QpeekBttn;
    private javax.swing.JButton SdisplayBttn;
    private javax.swing.JButton SpeekBttn;
    private javax.swing.JButton SpopBttn;
    private javax.swing.JButton SpushBttn;
    private javax.swing.JTextArea StackTArea;
    private javax.swing.JButton addcostuemrBttn;
    private javax.swing.JButton checkBttn;
    private javax.swing.JTextField costumerTField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton perfactBttn;
    private javax.swing.JTextArea prob1TArea;
    private javax.swing.JTextField prob1TField;
    private javax.swing.JTextArea prob2TArea;
    private javax.swing.JTextField prob3TField;
    private javax.swing.JTextArea prob3Tarea;
    private javax.swing.JTextArea queueTArea;
    private javax.swing.JTextField queueTField;
    private javax.swing.JButton redoBttn;
    private javax.swing.JButton servecostumerBttn;
    private javax.swing.JTextField stackTField;
    private javax.swing.JButton undoBttn;
    // End of variables declaration//GEN-END:variables
}
