/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FinalProjectGUI;

import java.util.Comparator;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.Stack;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Xyjor
 */
public class LibraryInventoryManagement extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LibraryInventoryManagement.class.getName());

    ArrayList<Book> books = new ArrayList<>();
    HashMap<String, Book> bookMap = new HashMap<>();
    Stack<Book> transactionStack = new Stack<>();
    DefaultTableModel tableModel;

    /**
     * Creates new form LibraryInventoryManagement
     */
    public LibraryInventoryManagement() {

        initComponents();

        String[] columns = {"ISBN", "Title", "Author", "Year", "Status"};
        tableModel = new DefaultTableModel(columns, 0);
        jTableDisplayBook.setModel(tableModel);
    }

    private void updateTable() {
        tableModel.setRowCount(0); // clear table
        for (Book b : books) {
            String status = b.isBorrowed ? "Borrowed" : "Available";
            tableModel.addRow(new Object[]{b.isbn, b.title, b.author, b.year, status});
        }
    }

    private void clearFields() {
        isbnTxtField.setText("");
        titleTxtField.setText("");
        authorTxtField.setText("");
        yearpubTxtField.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDisplayBook = new javax.swing.JTable();
        isbnTxtField = new javax.swing.JTextField();
        addBookBttn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        titleTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        authorTxtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        yearpubTxtField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        srchBttn = new javax.swing.JButton();
        sortTitleBttn = new javax.swing.JButton();
        sortYearBttn = new javax.swing.JButton();
        borrowBttn = new javax.swing.JButton();
        returnBttn = new javax.swing.JButton();
        undoBttn = new javax.swing.JButton();
        srchTxtField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        brrwrtrnTxtField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTableDisplayBook.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTableDisplayBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"0001", "Sword Art Online", "Reki Kawahara", "2009", null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ISBN (Book ID)", "Title", "Author", "Year", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableDisplayBook);

        isbnTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbnTxtFieldActionPerformed(evt);
            }
        });

        addBookBttn.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        addBookBttn.setText("Add Book");
        addBookBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookBttnActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BOOK DISPLAY");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("SimSun-ExtB", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Book Entry");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Enter ISBN:");

        titleTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleTxtFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Enter Title:");

        authorTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorTxtFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Enter Author:");

        yearpubTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearpubTxtFieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Enter Year Published:");

        srchBttn.setText("Search");
        srchBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchBttnActionPerformed(evt);
            }
        });

        sortTitleBttn.setText("Sort by Title");
        sortTitleBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortTitleBttnActionPerformed(evt);
            }
        });

        sortYearBttn.setText("Sort by Year");
        sortYearBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortYearBttnActionPerformed(evt);
            }
        });

        borrowBttn.setText("Borrow Book");
        borrowBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowBttnActionPerformed(evt);
            }
        });

        returnBttn.setText("Return Book");
        returnBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBttnActionPerformed(evt);
            }
        });

        undoBttn.setText("Undo Last Transaction");
        undoBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoBttnActionPerformed(evt);
            }
        });

        srchTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchTxtFieldActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Search Book by ISBN:");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Enter ISBN of Book to Borrow / Return:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(yearpubTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(isbnTxtField))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(titleTxtField)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(authorTxtField)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(addBookBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(borrowBttn)
                                        .addGap(18, 18, 18)
                                        .addComponent(returnBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(undoBttn))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(brrwrtrnTxtField))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(srchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(srchBttn)))))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(sortYearBttn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sortTitleBttn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(201, 201, 201))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(sortTitleBttn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sortYearBttn)
                                .addGap(9, 9, 9))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isbnTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titleTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(authorTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearpubTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addBookBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(srchBttn)
                    .addComponent(srchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(brrwrtrnTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrowBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(undoBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void isbnTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbnTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbnTxtFieldActionPerformed

    private void titleTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleTxtFieldActionPerformed

    private void authorTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_authorTxtFieldActionPerformed

    private void yearpubTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearpubTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearpubTxtFieldActionPerformed

    private void addBookBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookBttnActionPerformed
        String isbn = isbnTxtField.getText();
        String title = titleTxtField.getText();
        String author = authorTxtField.getText();
        String Year = yearpubTxtField.getText();
        int year;

        if (bookMap.containsKey(isbn)) {
            JOptionPane.showMessageDialog(rootPane, "Book already exists!");
            return;
        }

        if (isbn.isEmpty() && title.isEmpty() && author.isEmpty() && Year.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please input the following to add a book:\nISBN\nTitle\n"
                    + "Author\nYear Published", "", JOptionPane.ERROR_MESSAGE);
        } else if (isbn.isEmpty() || title.isEmpty() || author.isEmpty() || Year.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please Input Correctly", "", JOptionPane.ERROR_MESSAGE);
        }

        try {
            year = Integer.parseInt(yearpubTxtField.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Year must be in numbers!");
            return;
        }

        Book book = new Book(isbn, title, author, year);
        books.add(book);
        bookMap.put(isbn, book);
        updateTable();
        JOptionPane.showMessageDialog(rootPane, "Book Added Successfully");
        clearFields();
    }//GEN-LAST:event_addBookBttnActionPerformed

    private void borrowBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowBttnActionPerformed
        String isbn = brrwrtrnTxtField.getText();
        Book b = bookMap.get(isbn);

        if (b != null && !b.isBorrowed) {
            b.isBorrowed = true;
            transactionStack.push(b);
            JOptionPane.showMessageDialog(rootPane, "Book successfully borrowed!");
            updateTable();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Book unavailable or not found!");
        }
    }//GEN-LAST:event_borrowBttnActionPerformed

    private void returnBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBttnActionPerformed

        String isbn = brrwrtrnTxtField.getText();
        Book b = bookMap.get(isbn);

        if (b != null && b.isBorrowed) {
            b.isBorrowed = false;
            transactionStack.push(b);
            JOptionPane.showMessageDialog(rootPane, "Book Returned!");
            updateTable();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Invalid Return!");
        }
    }//GEN-LAST:event_returnBttnActionPerformed

    private void undoBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoBttnActionPerformed
        if (!transactionStack.isEmpty()) {
            Book b = transactionStack.pop();
            b.isBorrowed = !b.isBorrowed;
            JOptionPane.showMessageDialog(rootPane, "Last transaction undone!");
            updateTable();
        } else {
            JOptionPane.showMessageDialog(rootPane, "No transaction to undo!");
        }
    }//GEN-LAST:event_undoBttnActionPerformed

    private void sortTitleBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortTitleBttnActionPerformed
        Collections.sort(books, Comparator.comparing(book -> book.title));
        updateTable();
        JOptionPane.showMessageDialog(rootPane, "Books sorted by title!");
    }//GEN-LAST:event_sortTitleBttnActionPerformed

    private void sortYearBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortYearBttnActionPerformed
        Collections.sort(books, Comparator.comparingInt(book -> book.year));
        updateTable();
        JOptionPane.showMessageDialog(rootPane, "Books sorted by year!");
    }//GEN-LAST:event_sortYearBttnActionPerformed

    private void srchBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchBttnActionPerformed
        String isbn = srchTxtField.getText();
        Book b = bookMap.get(isbn);
        if (b != null) {
            JOptionPane.showMessageDialog(this,
                    "Found: " + b.title + " (" + b.year + ") - " + (b.isBorrowed ? "Borrowed" : "Available"));
        } else {
            JOptionPane.showMessageDialog(this, "Book not found!");
        }
    }//GEN-LAST:event_srchBttnActionPerformed

    private void srchTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srchTxtFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LibraryInventoryManagement().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBookBttn;
    private javax.swing.JTextField authorTxtField;
    private javax.swing.JButton borrowBttn;
    private javax.swing.JTextField brrwrtrnTxtField;
    private javax.swing.JTextField isbnTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDisplayBook;
    private javax.swing.JButton returnBttn;
    private javax.swing.JButton sortTitleBttn;
    private javax.swing.JButton sortYearBttn;
    private javax.swing.JButton srchBttn;
    private javax.swing.JTextField srchTxtField;
    private javax.swing.JTextField titleTxtField;
    private javax.swing.JButton undoBttn;
    private javax.swing.JTextField yearpubTxtField;
    // End of variables declaration//GEN-END:variables
}
